### ISSUE TITLE
Transducer loss leads to memory leak

### ISSUE THREAD

**Issue by YangHao97** [1ytic/warp-rnnt#21]
Hi, I'm using rnnt-loss and pytorch-lightning to train my model. But I found the 4D tensor which is used to calculate transducer will be accumulated in GPU, when I check the GPU memory in training step(before a batch starts), there are many 4D tensor(come from the previous batches) in the GPU memory. That will lead to CUDA out of memory finally. I don't know what went wrong.
![image](https://user-images.githubusercontent.com/71253402/126932421-114318fe-5bec-4935-a7cb-449d51a4a091.png)
gpu_tracker is used to check the GPU memory.
![image](https://user-images.githubusercontent.com/71253402/126932668-91f8057d-e5c8-4990-aeff-6722d0a40d2a.png)
The loss in training step is from this.
![image](https://user-images.githubusercontent.com/71253402/126932688-7ed35d12-5e2b-4c3e-9a36-075a745e4998.png)
This is the result of GPU memory usage in training step.
I try to use 'del', 'gc.collect()' and 'torch.cuda.empty_cache()' in everywhere, but they are all useless.

**Comment by 1ytic** [comment]
Hey, @YangHao97 Maybe the issue with the variable `transducer_loss`. Do not store it directly in `ret`. Try to reuse it and return a numpy array, or something like this.

**Comment by YangHao97** [comment]
Hi @1ytic , thanks for your reply.
I have changed the codes in figure 1 to the codes in figure 2, and it works. I'm not sure if different versions of pytorch, lightning and so on lead to this problem.
![image](https://user-images.githubusercontent.com/71253402/127201495-47193e14-4cf6-40ae-b18e-7ea12048a632.png)
                                                               figure 1

![image](https://user-images.githubusercontent.com/71253402/127201277-3b579fa4-02a8-4d72-a374-e7bd68666443.png)
                                                               figure 2

**Comment by 1ytic** [comment]
I'm still think that issue with the variable `transducer_loss`. You have to free it, instead of store it somewhere else. Anyway, if you have found the workaround, I'm happy for you.

**Comment by YangHao97** [comment]
Thank you so much!
